### ISSUE TITLE
Command Interface

### ISSUE THREAD

**Issue by michaelwisely** [redkyn/grader#2]
At the moment, it looks like usage is...

```
python run.py --image <my image> <the folder of assignments>
```

I was just thinking it might be nice to have a collection of subcommands for the grader tool:

```
# List available grader images, indicate a default image
python grader.py images

# Set the default image
python grader.py config default.image <my image>

# Grade the stuff
python grader.py grade --image <my image> <folder of assignments>

# Llist assignments, including their status (graded/not) and grade (if graded)
python grader.py assignments

# Show a specific assignment's details
python grader.py show <assignment id>

# Dump grade results to a file
python grader.py results > a_file

# Create some pretty results (read as LaTeX)
python grader.py generate-reports

# Clear out old assignments
python grader.py clear-all
```

It would be slick if there was a way to keep all the old assignment containers around and address them by assignment. Maybe something like `python grader.py --assignment=1 show xxx123` would show details for `xxx123`'s first assignment.

We could just drop a `.grader-config` file in the assignments directory to keep track of configuration of the tool.

I'm going to stop now before I get carried away. 

![O no. I'm losing it](https://i.imgur.com/uZqphfd.gif)

**Comment by brhoades** [comment]
I like all of this. I'm going to split these up into some separate issues.

**Comment by michaelwisely** [comment]
This is how it works now. Yay!
