### ISSUE TITLE
Buildout woes?

### ISSUE THREAD

**Issue by michaelwisely** [redkyn/grader#23]
@LinuxMercedes didn't you have trouble running buildout? I was able to set everything up on my box using the instructions in the README. Which version of Python are you using?

**Comment by LinuxMercedes** [comment]
I fixed it by sudo pip3 upgrading setuptools. Other than that, things have been fine.

**Comment by LinuxMercedes** [comment]
I think the only real problem here is buildout's error messages are obscure =/
